[project]
name = "pq-engine"
version = "0.1.0"
description = "pseudo quantum engine"
authors = [{ name = "bbrfkr", email = "bbrfkr@gmail.com" }]
requires-python = ">=3.13.0, <3.14"
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]
dependencies = ["numpy>=2.4.0, <2.5.0"]

[project.optional-dependencies]
gpu = ["cupy-cuda13x>=13.6.0, <13.7.0"]

[dependency-groups]
dev = [
    "ruff",
    "black",
    "mypy",
    "types-setuptools",
    "sphinx",
    "sphinx-rtd-theme",
    "setuptools",
]

[tool.uv]

[tool.uv.build-backend]
module-name = ["pq_engine"]
module-root = ""

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"

[lint]
lene-length = 88
select = ["E", "F", "I"]
fix = true

[tool.black]
line-length = 79

[tool.mypy]
ignore_missing_imports = true

