import importlib
import os
from typing import Any, Protocol, runtime_checkable, TypeGuard, cast


@runtime_checkable
class RandomModule(Protocol):
    def choice(self, a: Any, size=None, replace=True, p=None) -> Any: ...


@runtime_checkable
class LinalgModule(Protocol):
    def eigh(self, a: Any) -> Any: ...


@runtime_checkable
class ArrayModule(Protocol):
    array: Any
    complex64: Any
    ndarray: Any
    float32: Any
    linalg: LinalgModule
    random: RandomModule

    def dot(self, a: Any, b: Any = None) -> Any: ...
    def kron(self, a: Any, b: Any) -> Any: ...
    def conj(self, x: Any) -> Any: ...
    def transpose(self, x: Any) -> Any: ...
    def trace(
        x: Any, offset: Any = None, axis1: int = 0, axis2: int = 1
    ) -> Any: ...
    def reshape(self, x: Any, *args, **kwargs) -> Any: ...
    def prod(self, x: Any, axis: Any = None) -> Any: ...
    def allclose(
        a: Any, b: Any, rtol: float = 1e-5, atol: float = 1e-8
    ) -> bool: ...
    def sum(self, a: Any, axis: Any = None) -> Any: ...
    def add(self, x1: Any, x2: Any) -> Any: ...
    def divide(self, x1: Any, x2: Any) -> Any: ...
    def zeros(self, shape: Any, dtype: Any = None) -> Any: ...
    def identity(self, n: Any, dtype: Any = None) -> Any: ...
    def argsort(self, a: Any) -> Any: ...
    def unique(self, a: Any, return_index: bool = False) -> Any: ...
    def round(self, a: Any, decimals: int = 0) -> Any: ...
    def multiply(self, x1: Any, x2: Any) -> Any: ...
    def diag(self, v: Any, k: int = 0) -> Any: ...
    def arange(self, *args, **kwargs) -> Any: ...
    def inner(self, a: Any, b: Any) -> Any: ...


def is_array_module(module: Any) -> TypeGuard[ArrayModule]:
    """Type guard to verify module implements ArrayModule protocol."""
    return isinstance(module, ArrayModule)


#: atol value used by numpy or cupy.
atol = float(os.getenv("PQENGINE_ATOL", default="1.0e-5"))

#: rtol value used by numpy or cupy.
rtol = float(os.getenv("PQENGINE_RTOL", default="1.0e-5"))

#: approximation order of decimal used by numpy or cupy
rounded_decimal = int(os.getenv("PQENGINE_ROUNDED_DECIMAL", default="8"))

#: calculation engine (numpy or cupy)
array_engine: ArrayModule = cast(
    ArrayModule,
    (
        importlib.import_module("cupy")
        if os.getenv("PQENGINE_USE_GPU", default="")
        else importlib.import_module("numpy")
    ),
)
